# Generated by Django 2.2.3 on 2019-07-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='email',
            field=models.CharField(default='Empty...', max_length=30),
        ),
    ]
